### ISSUE TITLE
Function-name bikeshedding

### ISSUE THREAD

**Issue by Jamesernator** [js-choi/proposal-function-pipe-flow#3]
The current proposal uses `flow` and `pipe` as names for very similar concepts however it's not clear how "flow" distinguishes the behaviour from pipe.

Given `.pipe(initial, ...fns)` is essentially just `.flow(...fns)(initial)` I feel like a terminology like `.pipeline(...fns)` would make more sense. i.e. `.pipeline` creates a pipeline which can be passed a value, `.pipe` would be treatable as a shorthand for passing a value into a pipeline.

**Comment by ceigey** [comment]
I like the suggestion by @Jamesernator - an alternative could also be `createPipe` instead of `flow` (though this could imply that the _created_ `pipe` is an object, rather than specifically a function).

I guess something that is unavoidable is that `pipe` can be read as either a noun or a verb.

That said, I think `compose` tends to often imply the creation of a new unary function. But I don't know how heterodox `composeLeft` and `composeRight` might sound.

**Comment by js-choi** [comment]
I lifted `flow` from Lodash, thinking that community precedent would make its meaning clearer. But it’s true that it’s pretty similar sounding to `pipe`.

I am fine with renaming `flow` to `compose`, and I think I’ll use `compose` [when I present it to the TC39 plenary next week](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing).
(I like `pipeline` and `createPipe` less, since they are still pretty similar to `pipe` and have less precedent than either `flow` or `compose`.)

**Comment by shuckster** [comment]
> I am fine with renaming flow to compose

Perhaps I'm misunderstanding, but don't these two create their respective pipelines in opposite directions?

Something like:

    compose(3rd, 2nd, 1st)(x)

Vs:

    flow(1st, 2nd, 3rd)(x)
    pipe(x, 1st, 2nd, 3rd)

Have I got that wrong?

**Comment by js-choi** [comment]
Oh, yeah, right, now I remember; it’s been so long that I had forgotten:

The whole reason why I named it flow in the first place instead of compose was because compose usually refers to RTL composition. This makes it tougher to decide on a name. There’s also still the question on whether to make the function-composition function LTR or RTL (or whether to omit it and leave everything to `x=>Function.pipe(x,…)`), but that’s a different issue (#5).

**Comment by shuckster** [comment]
LTR, RTL... why not both? 😁

**Comment by getify** [comment]
Is the intent for these function(s) to be exposed as globals in JS programs, or to live in some namespace?

Like, will I literally have `flow` as a top-level built-in function (going to be SO MUCH namespace overlap with existing code) or will it more likely be something like `Function.flow`?

**Comment by js-choi** [comment]
@getify: These almost certainly would be static functions on the Function constructor, like `Function.flow`. And of course people would be free to destructure (e.g., `const { flow } = Function;`) if they feel like it.

**Comment by js-choi** [comment]
Due to its [rejection for Stage 1 on 2022-07](https://github.com/tc39/notes/blob/main/meetings/2022-07/jul-21.md#functionpipe--flow-for-stage-1), I’m withdrawing this proposal. I really appreciate everyone here giving discussion, though. (In the far future, after the pipe operator gains users, pain points with the pipe operator may be enough motivation to revive this proposal.) Happy trails to all.
