### ISSUE TITLE
Function composition: LTR flow vs. RTL compose

### ISSUE THREAD

**Issue by bergus** [js-choi/proposal-function-pipe-flow#5]
What about the standard function composition? I.e. `flow` with order of arguments reserved.
Why is it not part of this proposal? It would fit right in.

**Comment by js-choi** [comment]
This proposal used to have an RTL `compose`, but then we went back and forth over whether to match the LTR direction of `pipe` versus the RTL direction of mathematical function composition. 

I am confident that the Committee will balk at adding *three* similar functions—`pipe`, `flow`, and `compose`. (It may already be difficult enough to ask for two new functions `pipe` and `flow` instead of one new function, and we might have to end up dropping either `pipe` or `flow`.)

In other words, my feeling is that the Committee will be unenthusiastic about including both `flow` and `compose`, or `composeLeft` and `compose`, or whatever the pair would be named (see also #3).

We do need to talk about which we should include, assuming that we did have to pick one: a LTR `flow` or a RTL `compose`. LTR `_.flow` from Lodash has some significant usage. And, of course, RTL `compose` may fit the mental model of developers that use libraries like Ramda.

I will mention the possibility of having a RTL `compose` instead of a LTR `flow` in the [slides that I will present to the Committee plenary next week](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing).

**Comment by theScottyJam** [comment]
What are the arguments for the two directions? If we were to have both (just for the sake of argument), how would one decide when to use which?

**Comment by getify** [comment]
I think LTR is more favored for reading steps like an English sentence, logically in order, especially in an expression that will be immediately evaluated.

It's also nice how all the `|>` examples look, where the argument is at the top/start/left where it will actually be sent into.

However, in the function form that's more awkward, because you put the argument and the bottom/end/right, even though it weirdly flows back to the start of the list of functions.

```js
// nice
42 |> one |> two |> three

// weird
pipe(one,two,three)(42)

// better? 
compose(three,two,one)(42)
```

I think RTL (`compose(..)`) is more favored in that sense.

Moreover, RTL is generally more favored, from what I have seen in the FP world, when you're defining a function that will be used later. It's especially considered a bit more readable because of symmetry of source code syntax order:

```js
const f = v =>    three(two(one(v)));

const f = compose(three,two,one);
```

**Comment by bergus** [comment]
I'd prefer a proposal for both `compose` and `flow` (under whatever names), but leave `pipe` (that immediately applies) to the pipeline proposal. I think once you have values/variables, syntax wins over a helper function, function composition is more suitable for point-free programming.

**Comment by shuckster** [comment]
Is it realistic to expect the pipeline proposal would introduce a `pipe` function on-top of the new syntax of the Hack-pipe?

**Comment by shuckster** [comment]
Just to chip-in with a `compose` use-case:

Before:

```js
const renderBoard = () =>
  `
    <table class="board">
    <tbody>
      ${board
        .map(
          (row, py) =>
            `<tr>${row
              .map(
                (col, px) =>
                  `<td class="${
                    isDimmed(px, py, winningCombo) ? "dim" : ""
                  }" data-action="${
                    actions.SET_PIECE_DOWN
                  }" data-xy="${px},${py}">${cellAppearance[col]}</td>`
              )
              .join("")}</tr>`
        )
        .join("")}
    </tbody>
    </table>
  `;
```

After:

```js
const renderBoard = compose(
  (tbody) => `
    <table class="board">
    <tbody>
      ${tbody.join("")}
    </tbody>
    </table>
  `,
  (rows) => rows.map((col) => `<tr>${col.join("")}</tr>`),
  (board, winningCombo) =>
    board.map((row, py) =>
      row.map(
        (col, px) => `
        <td
          class="${isDimmed(px, py, winningCombo) ? "dim" : ""}"
          data-action="${actions.SET_PIECE_DOWN}"
          data-xy="${px},${py}"
        >
          ${cellAppearance[col]}
        </td>
      `
      )
    )
);
```

Both cases put through the Prettier grinder, so perhaps this is unconvincing/esoteric. But I thought I'd throw it out there anyway. Needless to say I like the `compose` version.

**Comment by getify** [comment]
I don't think we need a "pipe" function (the immediate application of the argument form)... because:

```js
42 |> flow(one,two,three)

// vs

pipe(42,one,two,three)
```

The former is one extra syntactic character but I'd argue is semantically much clearer.

In fact, I'd prefer that form over the noisier:

```js
42 |> one |> two |> three
```

**Comment by Avaq** [comment]
The exclusion of `compose` was a result of the argument I made here: https://github.com/tc39/proposal-function-helpers/issues/5

In a nutshell: *Aside from cases where the pipeline has the purpose of "wrapping" a structure as it goes (such as with lenses, transducers, or (XML) trees like in https://github.com/js-choi/proposal-function-pipe-flow/issues/5#issuecomment-1180390398), I believe that the RTL *uncurried/variadic* `compose` is just a less convenient form of LTR `flow`. The RTL `compose` function in my view really only (aside from aforementioned exception) makes sense if it's binary and curried, where it has a lot more utility.*

Please review the arguments made here for my line of thinking: https://github.com/tc39/proposal-function-helpers/issues/5#issue-1014332734

**Comment by js-choi** [comment]
I’m slowly coming around to @getify’s view that a `pipe` function is less important than either LTR composition and RTL composition. 

I do suspect that RTL composition will be a hard sell to the Committee without more specific use cases demonstrating that RTL composition is common or useful. “Symmetry of source code syntax order” is probably not a very compelling reason to the Committee in general why to include RTL `compose` *in addition* to LTR `flow`. Basically, what @Avaq said.

So, if I were to predict the Committee’s opinion, it would be that they might favor adding LTR `flow` alone the most, and not adding `pipe` or RTL `compose`.

I’ve edited the [plenary slides](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing) to emphasize our eight choices:

* Status quo
* LTR `flow`
* RTL `compose`
* LTR `flow` & RTL `compose`
* `pipe`
* `pipe` & LTR `flow`
* `pipe` & RTL `compose`
* `pipe`, `flow` & RTL `compose`

Please keep in mind that I am asking merely for Stage 1 at the plenary next week, which means that I am asking that the Committee formally consider this *problem space* to be worth exploring. I will present these possible solutions as what they are: tentative solutions for preliminary feedback. I’ll follow up here with the results of that preliminary feedback.

**Comment by Avaq** [comment]
> I don't think we need a "pipe" function (the immediate application of the argument form)... because [the F# pipeline operator solves this] -- @getify 

But it's very unlikely this operator will make it into the language. With the Hack operator we are more likely to get, your examples would read as:

```js
42 |> flow(one,two,three)(^)

// vs

pipe(42,one,two,three)

// and

42 |> one(^) |> two(^) |> three(^)
```

I prefer `pipe(42, one, two, three)` over both `42 |> flow(one, two, three)(^)` and `42 |> one(^) |> two(^) |> three(^)`. Am I missing something?

**Comment by js-choi** [comment]
@Avaq: Yes, you are correct: it would be `42 |> Function.flow(one, two, three)(^)`. (I’m not dismissing `Function.pipe` out of hand—I would find it useful too—but I do suspect the Committee will ask, “We are fine with `flow` but does `pipe` give that much extra benefit with `|>`? Nevertheless, [I will present `pipe` alongside `flow`, as well as RTL `compose`](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing). Let me know if you have any feedback on the plenary slides.)

**Comment by getify** [comment]
> But it's very unlikely this operator will make it into the language

I wasn't arguing for whatever the state of the `|>` proposal is... I stopped following it because I don't think it's a good feature and I don't plan to use it myself.

I personally would never prefer `42 |> flow(one,two,three)(^)` over just `flow(one,two,three)(42)`.

But even if we leave `|>` out of it, and we're just comparing:

```js
// (1)
pipe(42,one,two,three)

// (2)
flow(one,two,three)(42)

// (3)
compose(three,two,one)(42)
```

In order of preference, my votes are (3), (2), and (1) -- yes, pun intended here. And I think *that* is an even better argument for why RTL `compose(..)` is still needed.

**Comment by getify** [comment]
> without more specific use cases demonstrating that RTL composition is common

I've seen a lot of FP oriented code, especially JS code, and my belief is that RTL compose is far more common (whether it's binary or variadic) than LTR.

Moreover, most FP libraries have both forms, so it seems too myopic for the committee to just pick one or the other.

**Comment by Avaq** [comment]
In my day job, my colleagues and I write a lot of code with _fp-ts_, which implements (typed versions of) `pipe` and `flow` as currently presented in this proposal.

I might have a bias because of the tools we use, but I've also written a lot of code using Ramda, and I'm a core contributor to Sanctuary and have used it very extensively. It's actually my experience maintaining Ramda based code which has led me to my negative opinion on RTL compose as a tool for code linearization.

A quick search in one of our large `fp-ts` based projects shows 25 usages of `flow` and 262 usages of `pipe`. We try to use `flow` whenever we can for aesthetic reasons (point free looks pretty) but yet, we end up using `pipe` 10 times as much because in many data pipelines the input argument to `pipe` is reused somewhere else, or taken from an outer context.

**Comment by theScottyJam** [comment]
I had previously used Elm a bit which provides LTR and RTL for both pipe and compose, and I remember my own preference for them:
I would use LTR when I was putting each step on its own line, and RTL when I was putting it all on one line.

Having a RTL ordering for something like this makes sense:
```
const fn = compose(step3, step2, step1)
// later
fn(x)
```

(though, you probably could use either LTR of RTL here).

It's more jarring for something like this:
```
const fn = flow(
  step3,
  step2,
  step1,
);
// later
fn(value)
```

They make even more sense when you have operators that are pointing at the direction of flow, so you don't have to remember which name is associated with which direction.

**Comment by js-choi** [comment]
> I've seen a lot of FP oriented code, especially JS code, and my belief is that RTL compose is far more common (whether it's binary or variadic) than LTR.
> 
> Moreover, most FP libraries have both forms, so it seems too myopic for the committee to just pick one or the other.

@getify: Yeah—I myself would be fine with both. As we both know, the Committee is conservative when it comes to adding anything to the language. I’ve heard the phrase “but are there any specific use cases?” from engine implementors dozens of times during meetings—I can hear it already, even though the upcoming meeting is next week! 

To be fair, it is always better to be able to provide concrete evidence that developer experience would be significantly improved by a specific choice (such as including both LTR and RTL composition). 

So, ideally, what someone could do is a small survey of codebases to see if there are snippets that clearly demonstrate RTL composition being better than LTR composition. (I already did this on lodash-flow’s NPM dependencies, as well as open-source JavaScript repositories containing the word “pipe”.) This is a pre-Stage 2 concern, so we don’t have to worry too much about this yet, but it’s something that needs to eventually be done.

***

> I might have a bias because of the tools we use, but I've also written a lot of code using Ramda, and I'm a core contributor to Sanctuary and have used it very extensively. It's actually my experience maintaining Ramda based code which has led me to my negative opinion on RTL compose as a tool for code linearization. A quick search in one of our large fp-ts based projects shows 25 usages of flow and 262 usages of pipe. We try to use flow whenever we can for aesthetic reasons (point free looks pretty) but yet, we end up using pipe 10 times as much because in many data pipelines the input argument to pipe is reused somewhere else, or taken from an outer context.

@Avaq: This is fascinating data. Thank you! I would love any specific snippets that you can spare from your fp-ts–based codebase that might demonstrate the tradeoffs between fp-ts’s LTR `pipe` and RTL `compose`.

***

@theScottyJam: Elm remains one of my first post-Clojure loves. :smiley:

**Comment by shuckster** [comment]
@getify:

> ```js
> 42 |> flow(one,two,three)
> ```

Ah, the F# pipe. 😁

But yes, I agree with your proposition that `pipe(x, ...fns)` is unnecessary in view of the Hack-pipe proposal going through.

**Comment by getify** [comment]
Just to fill in one more detail that I don't like about `pipe(42,one,two,three)` style API, that I intended to type above and then it escaped my mind... :)

```js
pipe(anything,something,another)
```

That call-site does not make it obvious at all that `anything` is different in nature/type from `something` and `another`. When it's a value like `42` in our examples, it's more clear it's an argument. But when it's a variable (and who knows how well it's named), it's not nearly as clear that this is an argument into the composition, rather than part of the composition itself.

That's especially true since most other libraries that provide something like `pipe(..)` do so *without* providing the argument-application capability, they just create the composed function that still needs to be applied with an argument.

And it gets even more muddy if the value in that special first-argument position is itself a function... so now you have a list of functions, where the first function is the only one that gets treated differently -- it's never invoked, it's just passed in as a value.

I suspect that form of API, while a tiny bit convenient in some use cases, will be way more likely to trip people up with unexpected outcomes.

----

If I were you, I wouldn't even present it as an initial option, because I don't think it has sufficient justification (doesn't carry its own weight).

I think it should be on someone else on the committee to want it badly enough to push back on its absence with evidence of its value, rather than you presenting it as a (weak, I think) option in the proposal, which muddies the debate, and having it be something that's easily (and expectedly) called out as unnecessary.

**Comment by shuckster** [comment]
@js-choi:
> Nevertheless, [I will present `pipe` alongside `flow`, as well as RTL `compose`](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing). Let me know if you have any feedback on the plenary slides.)

I think I see a typo on page 3:

    Function.compose and
    Function.flowAsync
    (for LTR serial composition).

I guess that should be:

    Function.compose and
    Function.composeAsync
    (for RTL serial composition).

Also:

    Function.compose and Function.compose would be the same as Function.flow and Function.flowAsync but reversed.

To:

    Function.compose and Function.composeAsync would be the same as Function.flow and Function.flowAsync but reversed.

**Comment by getify** [comment]
Here's another way to view the debate of "Just one, or both": if you only ship one (whichever one), what's the expected likelihood that many code bases will just build the other out of the provided one?

```js
// have to define this manually, ugh
function flow(...fns) {
   return compose(...fns.reverse());
}
```

Or...

```js
// have to define this manually, ugh
function compose(...fns) {
   return pipe(...fns.reverse());
}
```

I can say for sure, on pretty much all of my FP projects, I would end up writing one or the other of those (or using some library that has it!) depending on which of the two (LTR or RTL) the JS language shipped natively.

Even if we assume the above 10-to-1 ratio (great data btw, thx!), where LTR is strongly preferred over RTL... the real metric is, how many code bases have ONLY one form of composition and not a single occurrence of the other form? I strongly suspect most full code bases make use of both forms, even if indeed the ratio is not very equal in either way.

**Comment by bergus** [comment]
> Please review the arguments made here for my line of thinking: [tc39/proposal-function-helpers#5 (comment)](https://github.com/tc39/proposal-function-helpers/issues/5#issue-1014332734)
>
>> ```js
>> Function.flow(Math.sin, Math.round, JSON.stringify)
>> ```
>> […] is both easier to read, and easier to refactor from and to
>> ```js
>> x => Function.pipe(x, Math.sin, Math.round, JSON.stringify)
>> ```

That's true, but on the other hand one would argue that
```js
Function.compose(JSON.stringify, Math.round, Math.sin)
```
is both easier to read, and easier to refactor from and to
```js
x => JSON.stringify(Math.round(Math.sin(x)))
```

>> Instead of the variadic compose function, [some problem] is best addressed by a unary curried function composition combinator

I doubt anyone could convince the committee to adopt curried functions into the standard library. This style of programming is just too niche in JavaScript. Hardly anybody would prefer to write
```js
const {compose} = Function;
const add = a => b => a + b;
const addThenSqrt = compose(compose(Math.sqrt), add);
console.log(addThenSqrt(140)(4))
```
over
```js
const {compose} = Function;
const add = (a, b) => a + b;
const addThenSqrt = (x, y) => Math.sqrt(add(x, y));
console.log(addThenSqrt(140, 4));
```
Even in Haskell, `(sqrt .) . (+)` / `(.) ((.) sqrt) (+)` is usually considered pointless, not just pointfree. If really necessary, people use a [separate operator](https://stackoverflow.com/questions/15029843/how-can-i-understand), like [`sqrt .: (+)`](https://hackage.haskell.org/package/composition-1.0.2.2/docs/Data-Composition.html#v:.:) - or they write `curry $ sqrt . uncurry (+)`.

**Comment by js-choi** [comment]
@shuckster: Thanks for spotting those typos in my slides; I fixed them.

**Comment by bergus** [comment]
> [I will present `pipe` alongside `flow`, as well as RTL `compose`](https://docs.google.com/presentation/d/1nkKKx26QuiqewGsl2gcTVFGd8HxRA_UBgtgQKdVpfQQ/edit?usp=sharing). Let me know if you have any feedback on the plenary slides.)

I think slide 3 should say `RTL` instead of `LTR` under `compose`

Edit: Oh I see @shuckster was faster than me

**Comment by js-choi** [comment]
Due to its [rejection for Stage 1 on 2022-07](https://github.com/tc39/notes/blob/main/meetings/2022-07/jul-21.md#functionpipe--flow-for-stage-1), I’m withdrawing this proposal. I really appreciate everyone here giving discussion, though. (In the far future, after the pipe operator gains users, pain points with the pipe operator may be enough motivation to revive this proposal.) Happy trails to all.
