### ISSUE TITLE
Should compose/flow return a variadic function (and what should its length be)?

### ISSUE THREAD

**Issue by bergus** [js-choi/proposal-function-pipe-flow#6]
```
const countArgs = (...args) => args.length;
const test = compose(countArgs);
console.log(test.length); // 1? Or same as countArgs.length?
console.log(test()); // 1 or 0?
console.log(test(null)); // 1, surely
console.log(test(null, null)); // 1 or 2?
```
The returned function might be variadic (having the same arity as the innermost function, and forwarding as many arguments as it receives), or it might be unary (having an arity of `1`, and forwarding only the first argument, or `undefined` if none is passed).

Both have their pros and cons. 
* The variadic solution would permit composing functions with multiple arguments without jumping through unnecessary hoops:

  ```js
  const add = (a, b) => a + b;
  const addThenSqrt = Function.compose(Math.sqrt, add); // (x, y) => Math.sqrt(add(x, y))
  console.log(addThenSqrt(140, 4)); // 12
  ```
  It would also fit in with the variadic behaviour of the `bind` method. On the other hand, such usage might be confusing to anyone coming from functional programming, all prior art I know works on unary functions exclusively. It would also be a bit harder to declare a correct type for it.
* A unary solution would follow prior art and have less surprises.

  ```js
  arrOfStrings.map(Function.compose(Math.sqrt, parseInt))
  ```
  would just work like `.map(x => Math.sqrt(parseInt(x)))` and not have [the `.map(parseInt)` problem](https://stackoverflow.com/q/262427/1048572). It could also be abused to create unary functions like in `arr.map(Function.compose(parseInt))` (not sure if that's a good or bad thing?).

**Comment by getify** [comment]
I strongly prefer unary-only return type.

**Comment by js-choi** [comment]
> "…all prior art I know works on unary functions exclusively.”

[Clojure’s comp function](https://clojuredocs.org/clojure.core/comp) creates a variadic function that passes all its arguments to the outermost callback. I’ve found that to be not surprising and sometimes useful. 

[Racket has both compose and compose1](https://docs.racket-lang.org/reference/procedures.html#%28def._%28%28lib._racket%2Fprivate%2Flist..rkt%29._compose%29%29). 

(I don’t remember what Scheme does.)

This might be a historical dichotomy between the prior art and expectations of Lisp-descending FP (which has n-ary functions) and Haskell-descending FP (unary functions).

**Comment by shuckster** [comment]
> [Clojure’s comp function](https://clojuredocs.org/clojure.core/comp) creates a variadic function that passes all its arguments to the outermost callback. I’ve found that to be not surprising and sometimes useful.

Suppose it's not the end of the world if it's unary since we have spread/rest, but I wanted to say I've also found use-cases for a variadic outer function in both `flow/pipe`/`compose`.

**Comment by js-choi** [comment]
See also the survey of [function composition forms in Lisps and other programming languages on Wikipedia](https://en.wikipedia.org/wiki/Function_composition_\(computer_science\)#Lisp).

**Comment by mAAdhaTTah** [comment]
There's actually, to some extent, two separate questions here:

1. What should the `.length` of the returned function be?
2. What behavior should the returned function have for the 2nd+ argument(s)?

[Ramda determines the arity of the function based on the arity of the first function](https://github.com/ramda/ramda/blob/master/source/pipe.js#L35-L38) and forwards all arguments, so prior art in JS favors the `length` matching the first function & forwarding all arguments to it. Note that those values aren't necessarily the same, as default arguments don't count towards the `length` of the function. In fact, `countArgs` in OP actually has a `length` of `0`.

**Comment by getify** [comment]
I've taught FP to a lot of JS devs, and I have regularly seen them get tripped up when dealing with compositions, when there's a different "rule" for the shape of the first function vs all the rest of the functions... that is, if the first function gets to be variadic (by virtue of the behavior of the result composed function) but all others have to be unary (because of the nature of single return values).

It's hard for them to fully understand why this restriction exists, even when it's been explained. And it's hard for them to remember until they've tripped on it a couple of times.

These are surmountable challenges, but... my experience was, it was far easier if, in all the examples we give for learners to understand and gain experience with the concept, we used only unary functions throughout the entire composition, instead of special-case'ing the first function.

----

Side note to consider: it might perhaps be useful -- although I can already hear people yelling "no!" at me for this idea -- for the utility to enforce unary-only, at least for every subsequent function if not for the first. It could for example require functions with length `0` or `1`, and reject any functions with length `2` or greater, since such a function is definitely going to behave improperly in the composition.

Remember that even a `param = default` will not end up getting counted in the length, so we're not actually forcing truly/purely unary functions, we'd just be saying that the function cannot be written in such a way as to *obviously expect* (non-optional) 2+ params, and have that be used in the subsequent positions of the composition, as there's really no viable way for that to behave correctly.

**Comment by js-choi** [comment]
> I've taught FP to a lot of JS devs, and I have regularly seen them get tripped up when dealing with compositions, when there's a different "rule" for the shape of the first function vs all the rest of the functions... that is, if the first function gets to be variadic (by virtue of the behavior of the result composed function) but all others have to be unary (because of the nature of single return values). It's hard for them to fully understand why this restriction exists, even when it's been explained. And it's hard for them to remember until they've tripped on it a couple of times. These are surmountable challenges, but... my experience was, it was far easier if, in all the examples we give for learners to understand and gain experience with the concept, we used only unary functions throughout the entire composition, instead of special-case'ing the first function.

Your educational experience is very valuable. Does this mean you observed developers attempting to apply multiple arguments to intermediate functions? Would they try to write things like `compose(h, g(1), f(0, 1))` to mean things like `x => h(g(f(x, 0, 1), 1))`, without combining them with partial function application?

As you know, the most upstream function in a chain of composed functions is indeed a special case, because the other functions are receiving return values. This is sort of a fundamental part of the concept, right? There’s no getting around the fact that the most upstream function in the chain is the only one not receiving a return value from another function. 

The fact that developers find this confusing is important to know, but I don’t know how much it would help to make the created function always unary. (In fact, I actually would *expect* `flow(f, g, h)(0, 1)` to work just like how I would expect `f(0, 1)` to work…and I would almost view not passing on additional arguments to the most upstream function as a weird special case that I would have to keep in mind whenever I use `flow`. I suspect other developers would be confused that `flow(f, g, h)(0, 1)` did not pass `1` to `f`. But these are only soft convictions.)

**Comment by shuckster** [comment]
@getify: I might contend that this is more an issue of how to go about teaching rather than something by which to set the standard by.

Kinda seems like one of those "wait, you can *do* that?" moments in-waiting for your students.

In my own case I'd use unary compositions the most. But I've found multiple args for the first function convenient enough to be included in my usual FP snippets.

**Comment by mAAdhaTTah** [comment]
> These are surmountable challenges, but... my experience was, it was far easier if, in all the examples we give for learners to understand and gain experience with the concept, we used only unary functions throughout the entire composition, instead of special-case'ing the first function.

I can understand the confusion, but I think you can teach this in this way without actually restricting the behavior of these functions.

---

> reject any functions with length `2` or greater, since such a function is definitely going to behave improperly in the composition.

Given JavaScript's long  pre-default args life, I don't think it's safe to assume that a `length > 1` means that the 2nd+ args are actually required. There also APIs that are "overloaded", whereby it lists 3 arguments, but works with 1, 2, or 3 args.

**Comment by getify** [comment]
When the students are first getting interested and learning about composition, they typically haven't yet learned about currying/PA yet. That sort of detail gets layered on, in my teaching, *after* they have learned about general composition. We literally revisit composition, once we have currying/PA in our toolbelt, and unlock the additional possibilities.

But when we're just talking about composition early on, we're first contending with how most developers aren't really all that used to thinking about functions as unary or binary or n-ary... so they just immediately seem to jump to, "oh, cool, I can wire ANY of my functions up in a composition".

And that's when it's useful, in my experience, to help them understand, because of return values, that really only unary functions should be in the composition, otherwise there's missing inputs and that will cause havoc. They often seem to *get that*.

But when you *then* start showing that the first step in the composition is *special* and gets to be n-ary, that seems to be the part that creates the cognitive overload, because then they start modifying compositions by adding new earlier steps, and their compositions then have multiple "middle steps" that are still binary/n-ary.

I faced that roadblock enough, that I switched my teaching to saying, early on, "we only do compositions with unary functions." It's easier for them to understand.

And then later, once they learn how currying/PA can re-shape higher-arity functions down to lower-arity (unary), they really seem to connect the dots and realize why that's so useful -- but importantly, *all* functions that get composed still end up unary, one way or the other.

Now, I basically never endorse in my teachings the "pass as many args into the first step as you want" style of composition, because, as I said, in my experience that was causing more tripping points than it was worth. I leave that to them to discover (or not) later.

**Comment by ljharb** [comment]
@mAAdhaTTah the length is *supposed* to always mean the number of required arguments, and that's how builtins work. A function that requires a different number of arguments is one that's misbehaving.

**Comment by getify** [comment]
I fully understand (and expected) for a bunch of people to disagree with me here. There's lots of different ways people approach this stuff. I'm just reporting my experiences with students. I don't think my observations necessarily mean that I wasn't teaching it to them well enough, and *that* was to blame. I think there are a lot of factors at play, and cognitive overload is a real (and highly studied) phenomenon. I think I just *learned* the hard way that it's often too much for most learners to juggle all at once.

YMMV, of course. But I would encourage comparing to other actual experience teaching folks rather than imagined or supposed or assumed teaching outcomes. It's a lot harder in the classroom than most people realize. :)

**Comment by js-choi** [comment]
> I basically never, now, endorse in my teachings the "pass as many args into the first step" style of composition, because, as I said, in my experience that was causing more tripping points than it was worth. I leave that to them to discover (or not) later.

I think this makes total sense. It’s how I learned about function composition in the first place, though that was in the context of Clojure.

Because JavaScript is a n-ary functional language (like Lisps) rather a unary functional language (like Haskell), there is something of an impedance mismatch when applying many unary-FP idioms to JavaScript. We all have experienced this before, when we’ve tried to interoperate between different libraries and APIs. And I think this also may manifest when novices who are used to n-ary APIs try to compose functions.

I think interoperability with n-ary functions is important enough that I probably would have flow/compose’s creations continue to accept n-ary inputs, while continuing to ignore this and teach students as if it were a unary function only. 

But I do appreciate the difficulty that novices have with learning about how it works in general, and it is always good to think about how to help them out. Thank you again for sharing your valuable experience as an educator, @getify.

***

@mAAdhaTTah: I think that, in the event that we choose to make the result of flow/compose n-ary and not always unary, then we would set the new function’s length property to be the same as the most-upstream function in the chain. Hopefully this makes sense.

**Comment by mAAdhaTTah** [comment]
@ljharb As one example off the top, `parseInt` has a `length` of `2` (as does `Number.parseInt`) but the radix is optional. I don't think it makes sense for `Function.pipe` to throw for valid compositions because someone implemented some userland function without properly considering its length when the builtins aren't all that consistent.

**Comment by ljharb** [comment]
@mAAdhaTTah not in code that follows best practices, it's not :-) and that's one of the most legacy functions in the language (Date is similarly mis-lengthed).

I do agree with you that builtins shouldn't be behaving differently based on a function's length, though.

**Comment by getify** [comment]
@mAAdhaTTah 

Can you give even a single non-contrived example of a function length > 0 that would still work normally and you'd want to use it in the middle of a unary composition?

JS has made quite a reputation since ES6 of throwing errors when devs do things that are clearly wrong/bad ideas/likely to be mistakes.

I cannot come up with any rational explanation for how using an n-ary function in the middle of a composition is not *almost always* wrong or a mistake.

**Comment by bergus** [comment]
@getify Real-world example:
```
function readFile(path, callback) {
   if (typeof callback == 'function') fs.readFile(path, callback);
   else return fs.promises.readFile(path);
}
```
<sup>(Far simplified implementation of course, but there are many APIs that work like this)</sup>
I would be really surprised (and annoyed) if
```
const readLines = composeAsync(splitLines, readFile, prefixDirectory)
```
would throw an exception based on `readFile.length` being `2`.

**Comment by ljharb** [comment]
@bergus fair, but in that situation you're also allowing someone to pass a non-function argument that'll be ignored, whereas i'd expect it to be `readFile(path, callback = undefined)` - making it optional, and including `if (typeof callback !== 'undefined') { throw something }` after the function check :-)

**Comment by bergus** [comment]
> 1. What should the `.length` of the returned function be?

I don't think that's a separate question to be discussed. Can we not all agree that 
* if the returned function is unary (forwarding exactly one argument), its `.length` will be `1`
* if the returned function is variadic (forwarding all arguments), its `.length` will have to match the `.length` of the first function to be called (and be `1` if no function was passed and the identity function is returned).

**Comment by mAAdhaTTah** [comment]
@getify Some examples that come to mind:

`parseInt` would work fine in a composition as a unary function.

I was also thinking of any function written pre-ES6 that takes an optional options-bag as the second argument. I've seen a decent amount of stuff that looks like this:

```js
function doSomethingToThing(thing, options) {
  if (!options) options = {}
  // validate options
  // then do something to thing
}
```

This certainly is a lot less common now that we have actual default args.

I've also definitely written overloaded functions that work fine with 1, 2 or 3 arguments and have done so "incorrectly" whereby the `length` was `3`.

Edit to add: In general, I don't think people are consistently doing a good job getting `length` correct in their API designs and I wouldn't want to punish the consumers of those functions for it by throwing.

---

@bergus I agree with that. The reason I wanted to flag it is `countArgs` has a length of `0`, so it wasn't obvious to me that passing in a 0-length function into `pipe` should return a 1-length function. But that makes sense.

**Comment by js-choi** [comment]
Due to its [rejection for Stage 1 on 2022-07](https://github.com/tc39/notes/blob/main/meetings/2022-07/jul-21.md#functionpipe--flow-for-stage-1), I’m withdrawing this proposal. I really appreciate everyone here giving discussion, though. (In the far future, after the pipe operator gains users, pain points with the pipe operator may be enough motivation to revive this proposal.) Happy trails to all.
